### PR TITLE
indexOf, lastIndexOf, map, keys, forEach, findIndex, find, join, includes, filter, every, fill ,entries

### PR DESCRIPTION
**Pull request by mubaidr**

### CODE REVIEW

**Comment by remy** [comment]
I won't merge this (so that others can use it), but I'm happy to give feedback - spotted a couple of bugs quickly scanning :)

**Comment by mubaidr** [comment]
Sure, please

**Comment by remy** [comment]
Actually, rather than doing a full review, here's my tests (as I was ill this w/e and decided to play at this code too 😄) https://gist.github.com/remy/a13c155eab3ade53c6abe1e8de7ee686

I'm not testing for `keys` or `values` yet, but I do do some more stringent tests on things like `copyWithin`.

**Comment by mubaidr** [comment]
Get well soon! 👍 

Thanks for sharing tests, this will surely help fix/improve code.

**Comment by remy** [comment]
I've made some more tests - on that same gist url - so you're welcome to take another run at them. Thanks again for finding the repo and practising 👍

**Pull request closed without merging**
